task:
  name: "Rom Builder"
  only_if: $CIRRUS_REPO_OWNER == 'Kartik-91'
  timeout_in: 120m
  container:
      image: ghcr.io/kartik-91/docker:ubuntu
      cpu: 4
      memory: 16G

    Sources:
      - source vars.sh

    Sync:
      - bash sync.sh

    Build:
      - bash build.sh

    Upload:
      - bash upload.sh
