version: 2.1

task:
  name: "Rom Builder"
  timeout_in: 120m
  container:
      image: ghcr.io/kartik-91/docker:ubuntu
      cpu: 4
      memory: 16G
    steps:
      - checkout

      - run:
          name: Source Vars
          command: |
            source vars.sh

      - run:
          name: Sync
          command: |
            bash sync.sh

      - run:
          name: Build
          command: |
            bash build.sh

      - run:
          name: Upload
          command: |
            export TIMEOUT=43200
            bash upload.sh
