env:

    # Config
    CONFIG: vars.sh

    CIRRUS_SHELL: bash

task:
  name: "Rom Builder"
  timeout_in: 120m
  container:
      image: ghcr.io/kartik-91/docker:ubuntu
      cpu: 8
      memory: 22G

    Sync:
      - curl -sL https://github.com/Kartik-91/ROM-Builder/raw/master/sync.sh | bash

    Build:
      - curl -sL https://github.com/Kartik-91/ROM-Builder/raw/master/build.sh | bash

    Upload:
      - export TIMEOUT=43200
      - curl -sL https://github.com/Kartik-91/ROM-Builder/raw/master/upload.sh | bash
