version: 2.1

jobs:
  build:
    docker:
      - image: ghcr.io/kartik-91/docker:ubuntu
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Source Vars
          command: |
            source vars.sh

      - run:
          name: Sync
          command: |
            bash sync.sh

      - run:
          name: Build
          command: |
            bash build.sh

      - run:
          name: Upload
          command: |
            export TIMEOUT=43200
            bash upload.sh
